[package]
name = "blastwa-setup"
version.workspace = true
edition.workspace = true

[[bin]]
name = "setup"
path = "src/main.rs"
test = false

[dependencies]
winreg = "0.52"
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
dirs = "5"
windows-sys = { version = "0.48", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Controls",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_Graphics_Gdi",
    "Win32_System_LibraryLoader",
    "Win32_System_Threading"
] }
